version: '3'
services:
  node:
    build: .
    restart: on-failure
    volumes:
      - ./src:/usr/app/src/
    command: npm start
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}

  postgres:
    build: ./database/
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/logs:z
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  postgres_data:
  postgres_logs:
